stages:
  - build

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # --- Build and push peaq ---
    - docker build -f Dockerfile.peaq -t $CI_REGISTRY_IMAGE:peaq-$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:peaq-latest .
    - docker push $CI_REGISTRY_IMAGE:peaq-$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:peaq-latest
    
    # --- Build and push etherlink ---
    - docker build -f Dockerfile.etherlink -t $CI_REGISTRY_IMAGE:etherlink-$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:etherlink-latest .
    - docker push $CI_REGISTRY_IMAGE:etherlink-$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:etherlink-latest