version: '3.8'

services:
  etherlink-cron:
    build:
      context: .
      dockerfile: Dockerfile.etherlink
    image: acelon-scripts-etherlink:latest
    container_name: acelon-etherlink-cron
    environment:
      - NODE_ENV=production
      - NETWORK=etherlink-mainnet
      - PRIVATE_KEY=${PRIVATE_KEY}
    restart: unless-stopped
    mem_limit: 512m
    cpus: "0.5"
    security_opt:
      - no-new-privileges:true
    user: "1000:1000"
    # Run every 10 minutes using bash loop
    command: >
      sh -c "
        while true; do
          echo '[$(date)] Running etherlink script...'
          node dist/etherlink/index.js
          echo '[$(date)] Sleeping for 10 minutes...'
          sleep 600
        done
      "